### ISSUE TITLE
Reshade Crashing Litcher

### ISSUE THREAD

**Issue by bythehist** [etra0/litcher#14]
After the 4.01 update and I have Version 5.6.0 of reshade installed, I launch the litcher while in game w/ the proper permissions, my game freezes and crashes to desktop. I went and uninstalled reshade, and litcher works fine. I also reinstalled witcher without Sweet FX and Otis' tools to see if they were the issue for some reason, but my game still crashed with even just the base reshade installed.

**Comment by etra0** [comment]
Hmm, do you receive any sort of message or it just simply closes?

I'll try to test it this weekend but no promises :P

**Comment by bythehist** [comment]
It just freezes and closes. I do get a witcher crash report once the game crashes to desktop. If there is any info from it that may help out , let me know and I can send the report your way. Thank you so much!! Seriously, no rush at all on this. I appreciate you and taking the time to help.

**Comment by bythehist** [comment]
Hey Erta, turned out I had hardware acceleration turned on for DLSS frame generation and thats what my issue was. Weird because I was using reshade with frame generation & litcher before and it was working fine before the update, I know others have been having issue running both reshade and frame generation though.

**Comment by etra0** [comment]
Oh, sadly, I don't have a 40x0 series to test that so sadly I won't be able to help you, so I think I'll close this issue as wontfix. I'm sorry.
